version: '3.8'
services:
  marginal-tax-calculator-api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - interview-test-server

  interview-test-server:
    image: ptsdocker16/interview-test-server:latest
    ports:
      - "5001:5001"
